// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_STRPRCLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_STRPRCLog));
        
        string IMigrationMetadata.Id
        {
            get { return "202306190840381_add_STRPRCLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
