// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTbl_EditReasons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTbl_EditReasons));
        
        string IMigrationMetadata.Id
        {
            get { return "202401310935265_addTbl_EditReasons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
