// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addIsExempField_StrprcTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsExempField_StrprcTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202401240543105_addIsExempField_StrprcTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
