// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPrintedOnField_PrintingLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPrintedOnField_PrintingLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "202404040334055_AddPrintedOnField_PrintingLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
