// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTbl_CompleteSTRPRC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTbl_CompleteSTRPRC));
        
        string IMigrationMetadata.Id
        {
            get { return "202403010027389_AddTbl_CompleteSTRPRC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
