// <auto-generated />
namespace PriceSignageSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeFields_TblQueues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeFields_TblQueues));
        
        string IMigrationMetadata.Id
        {
            get { return "202401180812425_removeFields_TblQueues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
